appName: crypteye-web

namespace: dev

image:
  name: crypteye-web
  pullPolicy: IfNotPresent
  tag: latest
  containerPort: 3000

resources:
  requests:
    cpu: 256m
    memory: 1000Mi
  limits:
    cpu: 256m
    memory: 1000Mi

restartPolicy: Always

replicaCount: 2
service:
  name: crypteye-web
  type: LoadBalancer
  targetPort: 3000
  port: 3000
